<?php
$htmldata .= "<article class=\"partneri_box\">
        <img src=\"assets/images/partneri/partneri.png?v=03\" width=\"776\" height=\"400\" alt=\"\" usemap=\"#partners\" />
      </article>
      <map name=\"partners\">
        <area shape=\"rect\" target=\"_blank\" target=\"_blank\" coords=\"45,39,174,93\" href=\"http://www.slsp.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"45,127,200,169\" href=\"http://www.kooperativa.sk/index.cfm\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"236,113,320,166\" href=\"http://www.telekom.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"338,123,463,162\" href=\"http://www.zse.sk/sk/Domacnosti\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"480,127,660,157\" href=\"http://datalan.sk/sk/domov\" alt=\"\" />

        <area shape=\"rect\" target=\"_blank\" coords=\"43,200,102,233\" href=\"http://www.zipp.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"113,198,165,238\" href=\"http://www.kon-rad.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"209,201,282,229\" href=\"http://www.schmidt-co.sk/vinoteka/o-spolocnosti\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"290,202,330,231\" href=\"\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"336,190,397,247\" href=\"http://www.eu-group.eu/\" alt=\"\" />

        <area shape=\"rect\" target=\"_blank\" coords=\"23,274,92,302\" href=\"http://www.rtvs.sk/sk/domov\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"23,310,85,338\" href=\"http://www.ta3.com/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"23,345,87,375\" href=\"http://www.jemnemelodie.sk/titulna-stranka\" alt=\"\" />

        <area shape=\"rect\" target=\"_blank\" coords=\"120,277,203,304\" href=\"http://www.tyzden.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"132,313,189,341\" href=\"http://www.zenskyweb.sk/kategoria/star\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"115,350,206,373\" href=\"http://www.zenskyweb.sk/kategoria/slovenka\" alt=\"\" />

        <area shape=\"rect\" target=\"_blank\" coords=\"226,266,339,300\" href=\"http://www.akzentmedia.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"236,306,328,331\" href=\"http://www.unimedia.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"223,343,341,365\" href=\"http://www.citylife.sk/\" alt=\"\" />

        <area shape=\"rect\" target=\"_blank\" coords=\"355,265,403,310\" href=\"http://www.musicpress.sk/\" alt=\"\" />

        <area shape=\"rect\" target=\"_blank\" coords=\"434,274,508,309\" href=\"http://www.bratislava.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"436,319,508,343\" href=\"http://www.staremesto.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"426,350,516,379\" href=\"http://www.nadaciapontis.sk/\" alt=\"\" />        

        <area shape=\"rect\" target=\"_blank\" coords=\"522,277,580,318\" href=\"http://www.abbabratislavahotel.com/sk/index.html\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"647,285,750,310\" href=\"http://cz.yamaha.com/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"585,273,647,319\" href=\"http://www.culture.gov.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"537,327,593,376\" href=\"http://www.albrechtforum.eu\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"600,330,655,370\" href=\"http://www.cef.sk/\" alt=\"\" />
        <area shape=\"rect\" target=\"_blank\" coords=\"660,330,730,370\" href=\"http://www.soza.sk/\" alt=\"\" />
      </map>";
?>