<?
$htmldata = '';
$htmldata .= "<article class=\"text_box tricka\">
      	<div class=\"text_box_wrap\">
          <div class=\"center\">
            <p class=\"text top\">Milí Viva fanúšikovia,</p>
						<p class=\"text\">možnosť rezervácie tričiek bola pozastavená.<br /> Odteraz si budete môcť tričká zakúpiť len počas festivalu od 23. - 30. Júna.</p>
						<p class=\"text\">Tešíme sa na vás!<br />Viva Team</p>
					</div>	
        </div>
      </article>";
?>