<?
$htmldata = '';
$htmldata .= "<article class=\"text_box tricka\">
      	<div class=\"text_box_wrap\">
          <div class=\"center\">
            <p class=\"text top\">Vytvor si tričko Viva Musica! podľa vlastného výberu! Vyber si svojho obľúbeného skladateľa, obľúbený strih či veľkosť a buď aj Ty v lete \"VivaMusica!-positive\"!</p>
						<p class=\"text\">Vyplnením nasledujúceho formuláru získaš rezerváciu trička na svoje meno.</p>
						<a href=\"\" class=\"trickoButton tricko0\" title=\"Dámske tielko\">
            	<img src=\"assets/images/tricka/tricko1.png\" width=\"123\" height=\"141\" alt=\"Dámske tielko\" />
              <span>Dámske tielko</span>
            </a>
            <a href=\"\" class=\"trickoButton tricko1\" title=\"Dámske tričko - dlhé\">
            	<img src=\"assets/images/tricka/tricko2.png\" width=\"123\" height=\"141\" alt=\"Dámske tričko - dlhé\" />
              <span>Dámske tričko dlhé</span>
            </a>
            <a href=\"\" class=\"trickoButton tricko2\" title=\"Dámske tričko - V výstrih\">
            	<img src=\"assets/images/tricka/tricko3.png\" width=\"123\" height=\"141\" alt=\"Dámske tričko - V výstrih\" />
              <span>Dámske tričko V výstrih</span>
            </a>
            <a href=\"\" class=\"trickoButton tricko3\" title=\"Pánske tričko\">
            	<img src=\"assets/images/tricka/tricko4.png\" width=\"123\" height=\"141\" alt=\"Pánske tričko\" />
              <span>Pánske tričko</span>
            </a>
            <section class=\"skladatelSelector\">
            	<div class=\"skladatelWrap\">
                <ul class=\"skladatel\">
                  <li><img src=\"assets/images/tricka/bach.png\" width=\"55\" height=\"67\" alt=\"Bach\" /></li>
                  <li><img src=\"assets/images/tricka/beethoven.png\" width=\"55\" height=\"67\" alt=\"Beethoven\" /></li>
                  <li><img src=\"assets/images/tricka/mozart.png\" width=\"55\" height=\"67\" alt=\"Mozart\" /></li>
                </ul>
              </div>
              <a class=\"arrow left\" href=\"\" title=\"Predchádzajúci\">Predchádzajúci</a>
              <a class=\"arrow right\" href=\"\" title=\"Ďalší\">Ďalší</a>
              <a class=\"vivabutton orange rot1 chcem\" href=\"\" title=\"Toto chcem\">Toto chcem</a>
            </section>
            <section class=\"velkost\">
            	<ul>
              	<li><a class=\"select rot1\" href=\"\" title=\"Veľkosť L\">L<span class=\"check\" style=\"display:inline;\"></span></a><span>L</span></li>
                <li><a class=\"select rot2\" href=\"\" title=\"Veľkosť M\">M</a><span>M</span></li>
                <li><a class=\"select rot3\" href=\"\" title=\"Veľkosť S\">S</a><span>S</span></li>
              </ul>
              <a class=\"vivabutton orange rot1 chcem\" href=\"\" title=\"Toto chcem\">Toto chcem</a>
            </section>
            <section class=\"kusov\">
            	<span>Mám záujem o</span>
              <input class=\"rot1\" type=\"text\" value=\"\" />
              <span>kusov.</span>
              <a class=\"vivabutton orange rot1 chcem\" href=\"\" title=\"Toto chcem\">Toto chcem</a>
            </section>
            <section class=\"form\">
            	<div class=\"row\">
                <label class=\"label label-name\">Viva Musica! tričko, prosím, zarezervovať na meno:</label>
                <input class=\"input1 rot1\" type=\"text\" name=\"name\" value=\"\" />
              </div>
              <div class=\"row\">
	              <label class=\"label label-email\">A E-mail:</label>
  	            <input class=\"input2 rot3\" type=\"text\" name=\"email\" value=\"\" />
              </div>
              <a href=\"\" title=\"Toto chcem\"><span class=\"rot1\">Chcem tricko</span><span class=\"bottom rot2\">Viva Musica!</span></a>
            </section>
						<section class=\"thx\">
							<p>Ďakujeme, práve ste sa stali Viva Positiv!</p>
							<a href=\"#/tricka\" title=\"Ešte jednu rezerváciu?\">Ešte jednu rezerváciu?</a>
						</section>
						<section class=\"steps\">
            	<ul>
              	<li class=\"krok1\"><a href=\"\" title=\"\"><span class=\"top\">Krok 1</span><span class=\"bottom\">Výber trička</span></a></li>
                <li class=\"krok2\"><a href=\"\" title=\"\"><span class=\"top\">Krok 2</span><span class=\"bottom\">Skladateľ</span></a></li>
                <li class=\"krok3\"><a href=\"\" title=\"\"><span class=\"top\">Krok 3</span><span class=\"bottom\">Výber veľkosti</span></a></li>
                <li class=\"krok4\"><a href=\"\" title=\"\"><span class=\"top\">Krok 4</span><span class=\"bottom\">Počet</span></a></li>
                <li class=\"krok5\"><a href=\"\" title=\"\"><span class=\"last\">Rezervácia</span></a></li>
              </ul>
            </section>
          </div>
        </div>
        <div class=\"text-box-right\">
        	<aside class=\"text\">
             <div class=\"scroll-pane trickaright jspScrollable\">
							<p>Tričká Viva Musica! v limitovanej \"2012\" edícii si bude možné zakúpiť len v rámci festivalového týždňa, t. j. od 23. do 30. júna 2012 osobne na VIVA MUSICA! INFO DESK-u v mieste konania koncertu.</p>
<p>Cena tričiek je jednotná: 10,- EUR.</p>
<p>Všetky tričká sú biele s čiernou potlačou.</p>
<p>Rezervácia trička je nezáväzná a vyplnením formuláru sa záujemca nezaväzuje ku kúpe trička. Rezervované tričká si je možné vyzdvihnúť do 25. júna 2012, najneskôr do 20:00 hod. Tričká, ktoré dovtedy nebudú vyzdvihnuté, budú vrátené naspäť do predaja.</p>
<p>Pre viac informácií kontaktujte, prosím, manažment Viva Musica! festivalu.</p>
             </div>
           </aside>
        </div>
      </article>";
?>