<?
$incdata = '';
$incdata .= "<article class=\"text_box vstupenky\">
      	<div class=\"text_box_wrap\">
          <div class=\"center\">
            <div class=\"scroll-pane festival jspScrollable\">
              ".$data['text_'.$lang]."
            </div>
          </div>
        </div>
      </article>";
$incdata .= "<img height=\"1\" width=\"1\" style=\"border-style:none;\" alt=\"\" src=\"http://www.googleadservices.com/pagead/conversion/1013868421/?label=e9zBCNO-4AMQhc-54wM&amp;guid=ON&amp;script=0\"/>";
?>